### ISSUE TITLE
Revisa el commit 

### ISSUE THREAD

**Issue by acsel21** [CamiloATP/Solemne_2#1]
Oye perro, esta listo para que cree la base de datos y agregue registros a persona y los lista.
Avisa para seguir implementando el resto.

**Comment by CamiloATP** [comment]
Se me había olvidado, lo termino y te aviso para subirlo voy a estar todo el día en esto....

**Comment by acsel21** [comment]
que agregaste al final ??

**Comment by acsel21** [comment]
oye perro, según el WireFrame de la solemne no pide listar el Rut.
si los sacamos no mas ?

**Comment by CamiloATP** [comment]
Se me olvido avisar que lo había subido xDD
